enum ERROR_CODE {
  NONE = 0,
  PLEASE_LOG_IN_TO_PERFORM_THIS_ACTION =  1,
  //createAccount
  CREATEACCOUNT_EXIST_USERINFO = 101,
  CREATEACCOUNT_EXIST_USERBASICINFO,
  CREATEACCOUNT_FAIL_INSERT_USERINFO,
  CREATEACCOUNT_FAIL_INSERT_BASICINFO,

  //editPassword
  EDITPASSWORD_FAIL_PASSWORD_UPDATE = 201,

  //editProfile
  FINDUSERCODE_FAIL_USERBASICINFO_UPDATE = 301,

  //findUserCode
  FINDUSERCODE_USER_NOT_FOUND = 401,

  //login
  LOGIN_USER_NOT_FOUND = 501,
  LOGIN_FAIL_INSERT_USERBASICINFO,
  LOGIN_INCORRECT_PASSWORD,

  //seeProfile
  SEEPROFILE_USER_NOT_FOUND = 601,

  //uploadProduct
  UPLOADPRODUCT_FAIL_INSERT_SELLINFO = 701,


  //followUser
  FOLLOWUSER_USER_NOT_FOUND = 801,

  //seeFollowers
  SEEFOLLOWERS_USER_NOT_FOUND = 901,


  //unFollowUser
  UNFOLLOWUSER_USER_NOT_FOUND = 1001,

  //seeFollowing
  SEEFOLLOWING_USER_NOT_FOUND = 1101,

  //seeProduct
  SEEPRODUCT_DONT_PRODUCT = 1201,

  //seeProductLikes
  SEEPRODUCTLIKE_DONT_PRODUCT = 1301,

  //sellInfo
  SELLINFO_DONT_USERBASICINFO = 1401,
  SELLINFO_DONT_HASHTAGS,
  SELLINFO_DONT_LIKE,

  //toggleLike
  TOGGLELIKE_DONT_PRODUCT = 1501,

  //seeFeed
  SEEFEED_DONT_PRODUCT = 1601,

  //deleteProduct
  DELETEPRODUCT_PRODUCT_NOT_FOUND = 1701,
  DELETEPRODUCT_NOT_AUTHORIZED,

  //createLocation
  CREATELOCATION_EXIST_USER = 1801,
  CREATELOCATION_FAIL_INSERT_USERLOCATION = 1802,
  CREATELOCATION_FAIL_INSERT_POSITIONLOCATION = 1803,
  CREATELOCATION_FAIL_INSERT_POSTLOCATION = 1804,

  //updateLocation
  UPDATELOCATION_USER_NOT_FOUND = 1901,
  UPDATEUSERSTATE_FAIL_UPDATE_STATE = 1902,
  UPDATELOCATION_FAIL_UPDATE_POSITIONLOCATION = 1903,
  UPDATELOCATION_POSTADDRESSCODEDEFINEINFO_NOT_FOUND = 1904,
  UPDATELOCATION_FAIL_UPDATE_POSTLOCATION = 1905,

  //userLocation
  USERLOCATION_DONT_POSITIONADDRESS = 2001,
  USERLOCATION_DONT_POSTADDRESS = 2002,

}
export default ERROR_CODE;

class error {
  constructor() {}
}